# Generated by Django 3.1 on 2020-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0002_auto_20200908_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideomodel',
            name='video_tags',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
