# Generated by Django 3.1 on 2020-09-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200824_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(1, 'World of Warcraft'), (3, 'League of Legends'), (2, 'Conter-Strike'), (0, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='core.film'),
        ),
    ]
