# Generated by Django 3.1 on 2020-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200908_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(3, 'League of Legends'), (1, 'World of Warcraft'), (0, 'Unknown'), (2, 'Conter-Strike')], default=0),
        ),
    ]
