# Generated by Django 3.1 on 2020-09-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200908_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(2, 'Conter-Strike'), (0, 'Unknown'), (1, 'World of Warcraft'), (3, 'League of Legends')], default=0),
        ),
    ]
