# Generated by Django 3.1 on 2020-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200908_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(2, 'Conter-Strike'), (3, 'League of Legends'), (0, 'Unknown'), (1, 'World of Warcraft')], default=0),
        ),
    ]
