# Generated by Django 3.1 on 2020-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200908_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (3, 'League of Legends'), (2, 'Conter-Strike'), (1, 'World of Warcraft')], default=0),
        ),
    ]
