# Generated by Django 3.1 on 2020-09-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200908_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Conter-Strike'), (1, 'World of Warcraft'), (3, 'League of Legends')], default=0),
        ),
    ]
